from chatbot.trainer import (
    T5_MODEL_NAME,
    T5_PROCESSOR_NAME,
    T5_VOCODER_NAME,
    WHISPER_MODEL_NAME,
    WHISPER_PROCESSOR_NAME,
)

T5_PROCESSOR_VERSION = f"{T5_PROCESSOR_NAME}:{{version}}"
T5_MODEL_VERSION = f"{T5_MODEL_NAME}:{{version}}"
T5_VOCODER_VERSION = f"{T5_VOCODER_NAME}:{{version}}"

WHISPER_PROCESSOR_VERSION = f"{WHISPER_PROCESSOR_NAME}:{{version}}"
WHISPER_MODEL_VERSION = f"{WHISPER_MODEL_NAME}:{{version}}"
